module.exports = {
    port : 7101,
    PLM_API: "http://bff-sr-01:7002/plm-api",
    // PLM_API: "http://localhost:7002/plm-api",
    ExcelIndex : {
        "IDX": 0,
        "DIVISION": 1,
        "SEASON": 2,
        "CATEGORY": 3,
        "PROGRAM": 4,
        "STYLE_NO_INDIVDUAL": 5,
        "GMT_DESCRIPTION": 6,
        "GMT_COLOR": 7,
        "NRF": 8,
        "GMT_COLOR_CODE": 9,
        "PACK_COMBINATION": 10,
        "PLACEMENT_NAME": 11,
        "BOM_SECTION": 12,
        "ITEM_NAME": 13,
        "SUPPLIER_NAME": 14,
        "RM_COLOR_NAME": 15,
        "CLR_DYE_TECH": 16,
        "RM_COLOR_REF": 17,
        "GARMENT_WAY": 18,
        "SUPPLIER_REF": 19,
        "MATERIAL_TYPE": 20
    },
    StyleHeader : "STYLE_NO_INDIVDUAL",
    BomDefaultName : "PRODUCTION BOM"
}